### ISSUE TITLE
TimeLapseBuilder build not running?

### ISSUE THREAD

**Issue by ghost** [acj/TimeLapseBuilder-Swift#1]
Good day,

I'm currently trying to use TimeLapseBuilder in my project, but it seems like it's not running.
I have the following function that runs when the user taps a button:

```swift
private func exportSpinsToVideo() {
    let timelapseBuilder = TimeLapseBuilder(photoURLs: spinURLs)
    timelapseBuilder.build({ progress in
      print(progress)
    }, success: { url in
      print(url)
    }, failure: { error in
      print(error)
    })
  }
```

When I tap the button I'm not getting any feedback from progress, success or failure.
The spinURLs String Array contains locations of images saved in the DocumentsDirectory.

Any idea as to what could be going wrong?

**Comment by acj** [comment]
Good day, @martisan!

My hunch is that your paths are incorrect or in the wrong format. The current error handling, especially for local files, isn't great. Be sure to include the `file://` prefix on local paths in your `spinURLs` array. 

You could try using `FileManager.default.fileExists(atPath: ...)` as a sanity check on your paths. Be sure _not_ to include the `file://` prefix on any paths you pass to it, though. :)

I've just pushed a fix that should cause the `failure` block to get called in this situation. Please let me know how it goes.

**Comment by ghost** [comment]
Hi @acj,

Thank you for the quick response. I've grabbed the latest and I'm now getting the following from the `failure` block: `UserInfo={description=AVAssetWriterInputPixelBufferAdapter failed to append pixel buffer}`.

My paths are: `/var/mobile/Containers/Data/Application/1BD97AD0-4163-4EFE-8BB2-BA41D7585C06/Documents/1493992961323/1.jpg`.

Should I maybe change my save function:
```swift
func createDirectoryForSpin() -> String {
    let documentsDirectory = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true).first!
    
    let spinDirectory = documentsDirectory.appending("/\(spinId)")
    print(spinDirectory)
    
    if !FileManager.default.fileExists(atPath: spinDirectory) {
      do {
        try FileManager.default.createDirectory(atPath: spinDirectory, withIntermediateDirectories: false, attributes: nil)
      } catch {
        print("Error creating directory: \(error.localizedDescription)")
      }
    } else {
      print("Directory already exists: \(spinDirectory)")
    }
    return spinDirectory
  }
  
  func saveCaptureToSpinDirectory(_ image: UIImage) {
    if let data = UIImageJPEGRepresentation(image, 1.0) {
      currentSpinCount += 1
      
      let fileName = spinDirectory.appending("/\(currentSpinCount).jpg")
      print("File Name: \(fileName)")
      
      if !FileManager.default.fileExists(atPath: fileName) {
        do {
          try data.write(to: URL(fileURLWithPath: fileName))
        } catch {
          print("Error: \(error.localizedDescription)")
        }
        
        spinURLs.append(fileName)
      } else {
        print("Image already exists at: \(fileName)")
      }
    }
  }
```

**Comment by acj** [comment]
Yep - it sounds like you'll need to prefix your paths with `file://` before
appending them to the array. Doing something like `URL(fileURLWithPath:
fileName).absoluteString` should handle that, or you could add the prefix
manually.

**Comment by ghost** [comment]
Hi @acj,

Thank you for all the help. I'm relatively new to `AVFoundation`.
Your suggestion indeed solved the problem I was experiencing.

Thank you for making this code available.

**Comment by acj** [comment]
@martisan I'm glad to hear that. AVFoundation can be overwhelming, but it's powerful and can be a lot of fun to use. Happy hacking!
