### ISSUE TITLE
how to set duration on picture frames?

### ISSUE THREAD

**Issue by MobileAppVault** [acj/TimeLapseBuilder-Swift#3]
Hi,

thanks for the nice piece of code. Just want to implement a parameter to set the duration between picture frame switch.

So I want to see a picture for 3 seconds but the framerate of the video file should be still 30 fps.

Is there a little tweak to make this possible?

Many thanks!

**Comment by acj** [comment]
That should be possible without changing too much code. The `presentationTime` value in [this loop](https://github.com/acj/TimeLapseBuilder-Swift/blob/master/TimeLapseBuilder/TimeLapseBuilder.swift#L88-L107) is what controls when each photo is shown. You'll need to change the loop to account for how long each photo should stay around. Good luck!
