### ISSUE TITLE
Video content start from left.

### ISSUE THREAD

**Issue by vijendravishwakarma** [acj/TimeLapseBuilder-Swift#5]
Hey 
I am creating the video from the number of image's URL. I am able to do that but I am facing a problem that when I have created the video that video content start from the top left and remaining screen shows black .
Thanks
Vijendra

**Comment by invinciible** [comment]
It's because of input size, try giving the right input size

**Comment by acj** [comment]
@vijendravishwakarma Sorry for the delay. As @invinciible noted, you may need to adjust the value of `inputSize` [here](https://github.com/acj/TimeLapseBuilder-Swift/blob/master/TimeLapseBuilder/TimeLapseBuilder.swift#L29) to match the dimensions of your images. Hope this helps.

**Comment by vijendravishwakarma** [comment]
@acj thanks for your response.Now I did it successfully.
