### ISSUE TITLE
Frame time calculation is a tiny bit out of whack

### ISSUE THREAD

**Issue by sjmills** [acj/TimeLapseBuilder-Swift#7]
Since my videos can have very low frame rates (down to 1fps), I noticed that the first frame of the finished video was lasting for 2 seconds when I changed the fps to 1. This is because the 2nd frame gets added at 2 seconds, not at 1 second. Only the `lastFrameTime` is needed:

```swift
let lastFrameTime = CMTimeMake(value: frameCount, timescale: fps)

if !self.appendPixelBufferForImageAtURL(nextPhotoURL, pixelBufferAdaptor: pixelBufferAdaptor, presentationTime: lastFrameTime) {
```

This correctly produces a video where the 1st and every frame truly lasts 1 second.

The `frameDuration` variable is also not needed with this change.

Thanks for this code, BTW. I was going to try to tackle it, but good grief! Why they didn't allow image types to be used with AVURLAsset is beyond common sense.

**Comment by acj** [comment]
Thanks for the fix! Yeah, it's surprising that Apple hasn't provided a baked-in solution to this. We can keep hoping :)
